# Generated by Django 5.2.7 on 2025-11-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
