# Generated by Django 5.2.7 on 2025-11-05 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_complaint_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='photo',
        ),
    ]
