# Generated by Django 5.2.7 on 2025-11-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_complaint_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='eco_points',
            field=models.IntegerField(default=0),
        ),
    ]
